# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='published_date',
        ),
    ]
