# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170611_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
