# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170611_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('type', 'name')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[(b'stacjonarne', b'stacjonarne'), (b'mobilne', b'mobilne')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategory', to='webapp.Category'),
        ),
    ]
