# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170611_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='last_modifed_date',
            new_name='last_modified_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='last_modifed_date',
            new_name='last_modified_date',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='last_modifed_date',
            new_name='last_modified_date',
        ),
    ]
