# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170611_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Asd',
                'verbose_name_plural': 'Asds',
            },
        ),
    ]
