# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_asd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asd',
        ),
    ]
