# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20170612_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
