# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_category_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
