# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_company_services_it_services_school_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
