# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20170623_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_description',
            new_name='shortDescription',
        ),
    ]
