# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20170623_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shortDescription',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
